name: Check Run Creator

on:
  push:
    branches:
      - main

permissions:
  checks: write

jobs:
  create-check-run:
    runs-on: ubuntu-latest
    steps:
      - name: Create Check Run
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/check-runs \
            -d '{
              "name": "Ping Google",
              "head_sha": "${{ github.sha }}",
              "status": "in_progress"
            }'
